server:
  port: 8089
  tomcat:
    uri-encoding: UTF-8
spring:
  redis:
    database: 1
    host: 192.168.0.224
    #host: 39.98.163.227
    port: 6379
    timeout: 3000000
    pool:
      max-active: 1000
      max-wait: 1
      max-idle: 10
      min-idle: 2
    password: aini123.321
  application:
    name: cms-server
  mvc:
    view:
      prefix: classpath*:/templates/
      suffix: .html
    static-path-pattern: /**
  datasource:
    url: jdbc:mysql://192.168.0.224:3306/qunqu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    #url: jdbc:mysql://39.98.163.227:3306/qunqu?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    #password: aini123.321
    password: XimenC2H
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  http:
    encoding:
      force: true
      charset: UTF-8
      enabled: true
  messages:
    encoding: UTF-8 
      
mybatis:
  mapper-locations: classpath*:mapper/*Mapper.xml
  type-aliases-package: com.foresee.model
  
logging:
  pattern:
    level: ERROR

#配置分页插件
pagehelper: 
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
      